---
- name: Install Postgres Debian
  apt: 
    name: postgresql
    state: latest
  when: ansible_os_family == "Debian"
  notify: Lancer le service postgreslq
  become: true

- name: Install postgres RedHat
  yum: 
    name: postgresql-server
    state: latest
  when: ansible_os_family == "RedHat"
  notify: Lancer le service postgreslq
  become: true
  