---
# tasks file for postgresql
- name: include vars
  include_vars: 
    file: main.yml
  tags: include_vars

- name: install postgres
  include_tasks: install.yaml
  tags: install

- name: install libraries
  include_tasks: install-dependecies.yaml
  tags: install

- name: start postgres
  include_tasks: start_service.yaml
  tags: start_postgresql

- name: create db
  include_tasks: create_db.yaml
  tags: creat_db"

- name: export db
  include_tasks: dumb_bd.yaml
  tags: export_db

- name: import db
  include_tasks: restore_db.yaml
  tags: import_db