---
- name: create service tomcat
  template: 
    src: roles/tomcat/templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  loop: "{{service}}"
  notify: 
    - daemon-reload
    - start_service
  become: true


